- name: This play will ping all docker containers
  hosts: all
  tasks:
    - name: Ping the container
      ping: 

    - name: Print IP Address of container 
      command: hostname -i
      register: output1 

    - debug: var=output1.stdout

    - name: Print the Name of the container
      command: hostname
      register: output2

    - debug: var=output2.stdout
